"""
utils.py
Utility functions shared across RF Explorer modules.
All code is functional-only: no UI / Rich printing here.
"""

import pkgutil
import re, os, shutil
from pathlib import Path
import subprocess
import warnings
import sysconfig
import logging
import importlib, inspect
from rich.table import Table
import importlib.metadata as md
from rich.console import Console
from robot.libdoc import LibraryDocumentation

warnings.filterwarnings("ignore")
logging.disable(logging.CRITICAL)
os.environ["PYTHONWARNINGS"] = "ignore"

# ---------------------------------------------------------------------------
# Code width utility for Rich Syntax formatting
# ---------------------------------------------------------------------------

def compute_code_width(lines, clamp=(20, 160)):
    """
    Compute a suitable width for a code block based on its longest line.

    Args:
        lines (list[str]): Lines of code.
        clamp (tuple): (min_width, max_width)

    Returns:
        int: Best-fit width.
    """
    max_len = max((len(l) for l in lines if l), default=0)
    width = max(clamp[0], min(clamp[1], max_len + 2))
    return width


# ---------------------------------------------------------------------------
# Docstring cleanup: remove inline "Description:" prefix
# ---------------------------------------------------------------------------

def strip_inline_description(doc_text: str) -> str:
    """
    Some Robot Framework libraries place:
        'Description: text...'
    on the same line. This causes duplicate Description sections.

    This function removes that inline prefix only.
    """

    if not doc_text:
        return doc_text

    first_line = doc_text.lstrip().split("\n", 1)[0].strip().lower()

    if first_line.startswith("description:"):
        # Remove only the prefix "Description:" and keep the rest
        return doc_text.split(":", 1)[1].lstrip()

    return doc_text


# ---------------------------------------------------------------------------
# RF doc section splitter (Description / Arguments / Examples)
# ---------------------------------------------------------------------------
def split_robot_sections(doc_text: str):
    """
    Split a RobotFramework docstring into:
    - description
    - arguments
    - examples (Robot code only)
    """

    if not doc_text:
        return {"description": "", "arguments": "", "examples": ""}

    doc_text = strip_inline_description(doc_text)

    # Patterns
    examples_pattern = r"(?im)^\s*(?:examples?|exemples?)\b.*:\s*"
    arguments_pattern = r"(?im)^\s*(?:arguments?|param[eè]tres?)\b.*:\s*"

    # Split text into description and after examples
    parts = re.split(examples_pattern, doc_text, maxsplit=1)
    description_part = parts[0].strip()
    examples = parts[1].strip() if len(parts) > 1 else ""

    # Extract Arguments section inside description
    parts2 = re.split(arguments_pattern, description_part, maxsplit=1)
    description = parts2[0].strip()
    argument_details = parts2[1].strip() if len(parts2) > 1 else ""

    return {
        "description": description,
        "arguments": argument_details,
        "examples": examples,
    }

# ---------------------------------------------------------------------------
# Cleanup generated log files generated by Libdoc
# ---------------------------------------------------------------------------
def delete_log_files(log_dir="."):
    logging.shutdown()

    root = Path(log_dir)

    for f in root.rglob("*.log"):
        try:
            f.unlink()
        except:
            pass

    folders = ("output", "outputs", "libdoc", "tmp", "temp")

    for d in root.iterdir():
        if d.is_dir() and d.name.lower() in folders:
            shutil.rmtree(d, ignore_errors=True)

# ---------------------------------------------------------------------------
# Robot Framework pipe-table → structured lines conversion
# ---------------------------------------------------------------------------

def convert_pipe_table(lines):
    """
    Convert a Robot Framework pipe-style table:
    """
    out = []

    for raw in lines:
        if "|" not in raw:
            return []

        # Split & clean
        cells = [c.strip() for c in raw.split("|") if c.strip()]
        if not cells:
            continue

        out.append("    " + "    ".join(cells))

    return out

console = Console()

# ---------------------------------------------------------------------------
# List all installed pip packages, with optional filter
# ---------------------------------------------------------------------------

def list_installed_packages(filter_value=None):
    """Display pip list using Rich, with optional filtering."""
    try:
        raw = subprocess.check_output(["pip", "list"], text=True)
    except Exception as e:
        console.print(f"[red]Error: {e}[/red]")
        return

    lines = raw.splitlines()[2:]  # Skip header

    filtered_rows = []

    for line in lines:
        if not line.strip():
            continue

        parts = line.split()
        if len(parts) < 2:
            continue

        pkg, ver = parts[0], parts[1]

        # Filter
        if filter_value and filter_value.lower() not in pkg.lower():
            continue

        filtered_rows.append((pkg, ver))

    # No results
    if filter_value and not filtered_rows:
        console.print(f"[yellow]No packages match the filter:[/yellow] {filter_value}")
        return

    console.print()
    console.print("Packages installed (pip list)\n", style="bold yellow")

    table = Table(show_header=True, header_style="bold")
    table.add_column("Package", style="cyan")
    table.add_column("Version", style="green")

    for pkg, ver in filtered_rows:
        table.add_row(pkg, ver)

    console.print(table)

# ---------------------------------------------------------------------------
# List RPA libraries (RPA.*, RPA.Email, RPA.Excel, etc.)
# ---------------------------------------------------------------------------

def list_rpa_libraries():
    libs = []

    # Charge Namespace RPA
    try:
        import RPA
    except ImportError:
        return libs

    # Parse RPA.*
    for _, mod1, _ in pkgutil.iter_modules(RPA.__path__):
        parent = f"RPA.{mod1}"

        # Add parent module
        libs.append(parent)

        # Explorer Sub modules : for example RPA.Email.* 
        try:
            pkg = importlib.import_module(parent)
            if hasattr(pkg, "__path__"):
                for _, mod2, _ in pkgutil.iter_modules(pkg.__path__):
                    full = f"{parent}.{mod2}"
                    libs.append(full)
        except Exception:
            pass

    return libs

# ---------------------------------------------------------------------------
# Return True if Standard Python module
# ---------------------------------------------------------------------------

def is_stdlib_module(module):
    """
    Return True if Python standard module  (os, sys, etc...)
    """
    try:
        path = os.path.realpath(getattr(module, "__file__", ""))
        if not path:
            return True  
        
        stdlib = os.path.realpath(sysconfig.get_paths()["stdlib"])
        
        # stdlib blocked
        if path.startswith(stdlib):
            return True
        
        # rest of site-packages → not blocked
        return False
    except Exception:
        return False

# ---------------------------------------------------------------------------
# Return True if a standard python module
# ---------------------------------------------------------------------------

def is_robot_library(name):

    BUILTIN_LIBRARIES = {
    "BuiltIn",
    "Collections",
    "DateTime",
    "Dialogs",
    "OperatingSystem",
    "Process",
    "Screenshot",
    "String",
    "Telnet",
    "XML"
    }

    if name in BUILTIN_LIBRARIES:
        return True

    # libdoc detection
    try:
        libdoc = LibraryDocumentation(name)
    except Exception:
        return False
    delete_log_files()

    # Must have keywords
    # if not any(not kw.name.startswith("_") for kw in libdoc.keywords):
    #     return False

    # Dynamic / hybrid / class libraries
    if getattr(libdoc, "library_type", None) in ("DYNAMIC", "HYBRID", "CLASS"):
        return True

    # Check Python classes for robot attributes
    try:
        module = importlib.import_module(name)
        for _, cls in inspect.getmembers(module, inspect.isclass):
            if any(hasattr(cls, a) for a in (
                "ROBOT_LIBRARY_VERSION",
                "ROBOT_LIBRARY_SCOPE",
                "ROBOT_LIBRARY_DOC_FORMAT"
            )):
                return True
    except Exception:
        pass

    try:
        dist = md.distribution(name)
        pkg = dist.metadata["Name"]

        if pkg.startswith("robotframework-"):
            return True

    except Exception:
        pass

    return False


